### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by drom** [simonswain/coldwar#2]
Awesome game :+1:, I want to fork and improve. Can you put some license file into repo?

**Comment by simonswain** [comment]
It's MIT. See the bottom of the README.

Thanks for the feedback :)

New version is coming soon, will be released 17th Nov at TalkJS in Singapore as part of @devfestasia

**Comment by drom** [comment]
I see. That was about `npm` was yelling at me, that it can't find `licenses` field inside `package.json`.
Looking forward seeing more updates ;)

**Comment by simonswain** [comment]
Has licence now.

**Comment by drom** [comment]
Great. Thank you!
