### ISSUE TITLE
Bug: FlashingScreen

### ISSUE THREAD

**Issue by Highrs** [simonswain/coldwar#3]
After the update that changed coldwar.io to a hub, all programs linked from it, including coldwar itself, started to flash on and off, rendering the gameplay impossible.

The flashes seem to intensify when more things are going on on the screen.

**Comment by simonswain** [comment]
I'm not seeing this issue. Can you let me know which browser/os you're getting it on?

Thanks for the feedback.

**Comment by Highrs** [comment]
I a, running Chrome on Linux OpenSuse.

This happens on only one of my computers. The other, weaker one has no such issue, even though it runs the same browser and OS.

Nothing similar happens with other items in chrome.

**Comment by simonswain** [comment]
What kind of computer? I'm running Chrome on a Thinkpad X220 with Ubuntu and not issue either. Wondering if the graphics card in that machine might be a problem. Especially since your other one is OK. Any idea what the graphics hardware in that machine is?

Thanks

**Comment by Highrs** [comment]
It would appear the issue disappeared when I just checked it. Perhaps a chrome bug?

Sorry for the mishap :)

**Comment by simonswain** [comment]
No problem thanks for the feedback. Let me know if you find anything else
or have any ideas for additions.

On Tuesday, 1 December 2015, Operator Fall notifications@github.com wrote:

> It would appear the issue disappeared when I just checked it. Perhaps a
> chrome bug?
> 
> Sorry for the mishap :)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/simonswain/coldwar/issues/3#issuecomment-160786810.

## 

Simon Swain
+61 418 30 20 20
@simon_swain
